# Generated by Django 4.1 on 2022-12-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileEmailVerification',
        ),
    ]
