# Generated by Django 4.1.4 on 2022-12-18 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MPR_member', to='core.member')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MPR_program', to='core.program')),
            ],
        ),
    ]
