# Generated by Django 4.1.4 on 2023-01-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_edmr_remove_education_description_club_enrollers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
