# Generated by Django 4.1.4 on 2022-12-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mpr'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpr',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
