# Generated by Django 4.1.4 on 2023-01-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_diet_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='day',
        ),
    ]
