# Generated by Django 4.1.4 on 2023-01-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_event_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='enrollers',
            field=models.ManyToManyField(blank=True, related_name='enrollings', to='core.userprofile'),
        ),
    ]
