# Generated by Django 4.1.4 on 2023-01-19 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_club_enrollers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Blogs', to='core.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='BMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLiked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BMR_blog', to='core.blog')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BMR_member', to='core.member')),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='EdMR',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
