# Generated by Django 4.1.4 on 2023-01-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blog_bmr_remove_education_trainer_delete_edmr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='trainer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='core.trainer'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_club', to='core.club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_member', to='core.member')),
            ],
        ),
    ]
