# Generated by Django 4.1.4 on 2023-01-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blog_trainer_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UTR_user', to='core.userprofile')),
            ],
        ),
    ]
